"""Email notification for pod failures."""
import logging
import os
import smtplib
import time
from dataclasses import dataclass
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


@dataclass
class PodFailure:
    """Type hint for PodFailure from watcher.py."""
    namespace: str
    pod_name: str
    reason: str
    restart_count: int


@dataclass
class InvestigationResult:
    """Type hint for InvestigationResult from investigator.py."""
    question: str
    answer: str
    tool_calls: list
    iterations: int
    provider: str


@dataclass
class EmailConfig:
    """SMTP email configuration loaded from environment."""
    smtp_host: str
    smtp_port: int
    smtp_user: str
    smtp_password: str
    smtp_from: str
    smtp_use_tls: bool
    alert_email_to: list[str]
    
    @classmethod
    def from_env(cls) -> "EmailConfig":
        """Load email config from environment variables."""
        to_addrs = os.getenv("ALERT_EMAIL_TO", "")
        return cls(
            smtp_host=os.getenv("SMTP_HOST", "smtp.gmail.com"),
            smtp_port=int(os.getenv("SMTP_PORT", "587")),
            smtp_user=os.getenv("SMTP_USER", ""),
            smtp_password=os.getenv("SMTP_PASSWORD", ""),
            smtp_from=os.getenv("SMTP_FROM", ""),
            smtp_use_tls=os.getenv("SMTP_USE_TLS", "true").lower() == "true",
            alert_email_to=[addr.strip() for addr in to_addrs.split(",") if addr.strip()]
        )


class EmailNotifier:
    """Sends email alerts for pod failures."""
    
    def __init__(self, config: EmailConfig):
        self.config = config
    
    def send_alert(self, failure: PodFailure, result: InvestigationResult, severity: str) -> None:
        """Send email alert with retry logic.
        
        Args:
            failure: Pod failure details
            result: Investigation result
            severity: Severity level (CRITICAL, HIGH, MEDIUM, LOW)
        """
        if not self.config.alert_email_to:
            logger.warning("No email recipients configured, skipping alert")
            return
        
        if not self.config.smtp_user or not self.config.smtp_password:
            logger.warning("SMTP credentials not configured, skipping alert")
            return
        
        plain_body = self._format_email(failure, result, severity)
        html_body = self._build_html_body(failure, result, severity)
        subject = f"[{severity}] KubeSherlock Alert: {failure.namespace}/{failure.pod_name}"
        
        # Retry with exponential backoff: 0s, 5s, 15s
        delays = [0, 5, 15]
        for attempt, delay in enumerate(delays, 1):
            if delay > 0:
                time.sleep(delay)
            
            try:
                self._send_smtp_multipart(subject, plain_body, html_body)
                logger.info(f"Alert sent successfully (attempt {attempt})")
                return
            except Exception as e:
                logger.error(f"Failed to send email (attempt {attempt}/{len(delays)}): {e}")
                if attempt == len(delays):
                    logger.error("All retry attempts exhausted, alert not sent")
    
    def _format_email(self, failure: PodFailure, result: InvestigationResult, severity: str) -> str:
        """Format plain text email body."""
        kubectl_ns = f"kubectl -n {failure.namespace}"
        return f"""KubeSherlock Investigation Report

SEVERITY: {severity}
POD: {failure.namespace}/{failure.pod_name}
REASON: {failure.reason}
RESTART COUNT: {failure.restart_count}
PROVIDER: {result.provider}
ITERATIONS: {result.iterations}

ROOT CAUSE ANALYSIS:
{result.answer}

DIAGNOSTIC COMMANDS:
{kubectl_ns} describe pod {failure.pod_name}
{kubectl_ns} logs {failure.pod_name} --previous
{kubectl_ns} get events --field-selector involvedObject.name={failure.pod_name}
{kubectl_ns} top pod {failure.pod_name}

---
Generated by KubeSherlock
"""
    
    def _build_html_body(self, failure: PodFailure, result: InvestigationResult, severity: str) -> str:
        """Build HTML email body with professional template."""
        kubectl_ns = f"kubectl -n {failure.namespace}"
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        # Severity color mapping
        severity_colors = {
            "CRITICAL": "#dc3545",
            "HIGH": "#fd7e14",
            "MEDIUM": "#ffc107",
            "LOW": "#0dcaf0"
        }
        badge_color = severity_colors.get(severity, "#6c757d")
        
        # Escape HTML in dynamic content
        def escape(text: str) -> str:
            return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        
        html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;background-color:#f5f5f5;">
<table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:20px 0;">
<tr>
<td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background-color:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);">
<!-- Header -->
<tr>
<td style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:30px;text-align:center;">
<h1 style="margin:0;color:#ffffff;font-size:28px;font-weight:600;">🔍 KubeSherlock</h1>
<p style="margin:8px 0 0 0;color:#ffffff;font-size:14px;opacity:0.9;">Investigation Report</p>
</td>
</tr>
<!-- Severity Badge -->
<tr>
<td style="padding:30px 30px 20px 30px;text-align:center;">
<span style="display:inline-block;background-color:{badge_color};color:#ffffff;padding:8px 16px;border-radius:20px;font-size:14px;font-weight:600;letter-spacing:0.5px;">{escape(severity)}</span>
</td>
</tr>
<!-- Pod Details -->
<tr>
<td style="padding:0 30px 20px 30px;">
<table width="100%" cellpadding="8" cellspacing="0" style="border:1px solid #e0e0e0;border-radius:6px;">
<tr style="background-color:#f8f9fa;">
<td style="padding:12px;font-weight:600;color:#495057;border-bottom:1px solid #e0e0e0;">Pod</td>
<td style="padding:12px;color:#212529;border-bottom:1px solid #e0e0e0;font-family:monospace;">{escape(failure.namespace)}/{escape(failure.pod_name)}</td>
</tr>
<tr>
<td style="padding:12px;font-weight:600;color:#495057;border-bottom:1px solid #e0e0e0;">Reason</td>
<td style="padding:12px;color:#212529;border-bottom:1px solid #e0e0e0;">{escape(failure.reason)}</td>
</tr>
<tr style="background-color:#f8f9fa;">
<td style="padding:12px;font-weight:600;color:#495057;border-bottom:1px solid #e0e0e0;">Restart Count</td>
<td style="padding:12px;color:#212529;border-bottom:1px solid #e0e0e0;">{failure.restart_count}</td>
</tr>
<tr>
<td style="padding:12px;font-weight:600;color:#495057;border-bottom:1px solid #e0e0e0;">Provider</td>
<td style="padding:12px;color:#212529;border-bottom:1px solid #e0e0e0;">{escape(result.provider)}</td>
</tr>
<tr style="background-color:#f8f9fa;">
<td style="padding:12px;font-weight:600;color:#495057;">Iterations</td>
<td style="padding:12px;color:#212529;">{result.iterations}</td>
</tr>
</table>
</td>
</tr>
<!-- Root Cause Analysis -->
<tr>
<td style="padding:0 30px 20px 30px;">
<h2 style="margin:0 0 12px 0;color:#212529;font-size:18px;font-weight:600;">Root Cause Analysis</h2>
<div style="background-color:#f8f9fa;border-left:4px solid #667eea;padding:16px;border-radius:4px;color:#212529;line-height:1.6;">
{escape(result.answer).replace(chr(10), '<br>')}
</div>
</td>
</tr>
<!-- Diagnostic Commands -->
<tr>
<td style="padding:0 30px 30px 30px;">
<h2 style="margin:0 0 12px 0;color:#212529;font-size:18px;font-weight:600;">Diagnostic Commands</h2>
<div style="background-color:#1e1e1e;border-radius:6px;padding:16px;overflow-x:auto;">
<pre style="margin:0;color:#d4d4d4;font-family:'Courier New',Courier,monospace;font-size:13px;line-height:1.6;white-space:pre-wrap;word-wrap:break-word;"><code>{escape(kubectl_ns)} describe pod {escape(failure.pod_name)}
{escape(kubectl_ns)} logs {escape(failure.pod_name)} --previous
{escape(kubectl_ns)} get events --field-selector involvedObject.name={escape(failure.pod_name)}
{escape(kubectl_ns)} top pod {escape(failure.pod_name)}</code></pre>
</div>
</td>
</tr>
<!-- Footer -->
<tr>
<td style="padding:20px 30px;background-color:#f8f9fa;border-top:1px solid #e0e0e0;text-align:center;">
<p style="margin:0;color:#6c757d;font-size:12px;">Generated by KubeSherlock</p>
<p style="margin:4px 0 0 0;color:#6c757d;font-size:12px;">{escape(timestamp)}</p>
</td>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>"""
        return html
    
    def _send_smtp_multipart(self, subject: str, plain_body: str, html_body: str) -> None:
        """Send multipart email via SMTP with HTML and plain text."""
        # Create message container
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.config.smtp_from
        msg["To"] = ", ".join(self.config.alert_email_to)
        
        # Attach plain text first (fallback)
        msg.attach(MIMEText(plain_body, "plain"))
        # Attach HTML (preferred)
        msg.attach(MIMEText(html_body, "html"))
        
        if self.config.smtp_use_tls:
            server = smtplib.SMTP(self.config.smtp_host, self.config.smtp_port, timeout=10)
            server.starttls()
        else:
            server = smtplib.SMTP(self.config.smtp_host, self.config.smtp_port, timeout=10)
        
        try:
            server.login(self.config.smtp_user, self.config.smtp_password)
            server.sendmail(self.config.smtp_from, self.config.alert_email_to, msg.as_string())
        finally:
            server.quit()
