"""
k8s_mcp.tools.events
~~~~~~~~~~~~~~~~~~~~

Kubernetes event retrieval, focused on Warning-type events used for
incident triage (OOMKilled, BackOff, FailedScheduling, etc.).

Classes:
    Event       — structured representation of a single Kubernetes event.
    EventsTool  — stateless tool class; injected with a client and security context.
"""

import logging
from dataclasses import dataclass

from ..client import K8sClient
from ..security import SecurityContext

log = logging.getLogger(__name__)


@dataclass
class Event:
    """A single Kubernetes event.

    Attributes:
        name: Event object name (auto-generated by Kubernetes).
        reason: Short machine-readable reason (e.g. ``OOMKilling``,
            ``BackOff``, ``FailedScheduling``).
        message: Human-readable description of the event.
        type: ``Normal`` or ``Warning``.
        involved_object: ``Kind/name`` string of the object this event
            refers to (e.g. ``Pod/payment-api-6d4f9``).
        count: Number of times this event has occurred.
    """

    name: str
    reason: str
    message: str
    type: str
    involved_object: str
    count: int


class EventsTool:
    """Retrieves Kubernetes events for incident triage.

    Args:
        client: Shared :class:`~k8s_mcp.client.K8sClient` instance.
        security: :class:`~k8s_mcp.security.SecurityContext` for the current
            session — enforces namespace ACLs before any API call.
    """

    def __init__(self, client: K8sClient, security: SecurityContext) -> None:
        self._client = client
        self._security = security

    def get_events(self, namespace: str, warnings_only: bool = True) -> list[Event]:
        """Return Kubernetes events for *namespace*.

        Args:
            namespace: Kubernetes namespace to query.
            warnings_only: When ``True`` (default), only ``Warning`` type
                events are returned.  Set to ``False`` to include ``Normal``
                events as well.

        Returns:
            List of :class:`Event` objects.  Empty list if no matching events.

        Raises:
            PermissionError: If *namespace* is not in the session's allowlist.
        """
        log.debug(
            "get_events  namespace=%s  warnings_only=%s", namespace, warnings_only
        )
        self._security.check_namespace(namespace)
        raw = self._client.core.list_namespaced_event(namespace)
        result = [
            Event(
                name=e.metadata.name,
                reason=e.reason or "",
                message=e.message or "",
                type=e.type or "",
                involved_object=f"{e.involved_object.kind}/{e.involved_object.name}",
                count=e.count or 1,
            )
            for e in raw.items
            if not warnings_only or e.type == "Warning"
        ]
        log.info(
            "get_events  namespace=%s  warnings_only=%s  count=%d",
            namespace, warnings_only, len(result),
        )
        return result
